### ISSUE TITLE
Uncaught TypeError: parameters.join is not a function

### ISSUE THREAD

**Issue by Assada** [aaronlord/laroute#22]
![](http://i.imgur.com/KPlPK0O.png)

```javascript
var ajaxurl = laroute.url('ajax-'+$(this).data('action'), []);
```

**Comment by aaronlord** [comment]
Do you have any more details on this?

Based on what you've presented, an error is being thrown for essentially `[].join('/')` (which is vanilla js and shouldn't error).

**Comment by waqasraza123** [comment]
I have this error too what should i do? @aaronlord

**Comment by aaronlord** [comment]
What parameters are you passing to the `laroute.url` call?

**Comment by waqasraza123** [comment]
url to my route like `home` @aaronlord

**Comment by richiej053** [comment]
The problem is you are not passing in the 2nd parameter so you are trying to call .join on null, try passing in an empty array url('home/index', [])

**Comment by waqasraza123** [comment]
why we are passing null as second argument?

On Fri, Jan 15, 2016 at 4:31 PM, richiej053 <notifications@github.com>
wrote:

> The problem is you are not passing in the 2nd parameter so you are trying
> to call .join on null, try passing in an empty array url('home/index', [])
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aaronlord/laroute/issues/22#issuecomment-171938647>.
>



-- 
WAQAS RAZA <https://www.odesk.com/users/~0117b5cb460d5341a5>
Student at NUST , SEECS
Web Developer at UpWork (Formerly odesk)

**Comment by 3amprogrammer** [comment]
The problem is here:
```
// Generate a fully qualified URL to the given path.
// laroute.route('url', [params = {}])
url : function (route, parameters) {
    parameters = parameters || {};

    return routes.url(route, parameters);
},
```

If you don't pass any parameter an empty object is assigned by default. In next step there is a check if parameters variable is empty:
```
url: function (url, parameters) {
    parameters = parameters || [];

    var uri = url + '/' + parameters.join('/');

    return this.getCorrectUrl(uri);
},
```

But its not. `parameters = parameters || [];` this line is wrong. An empty object passed to this function happens to be true ({} == true after coercion).

**Comment by meteorlxy** [comment]
@3amprogrammer I think it's a mistake and should be fixed.

**Comment by Assada** [comment]
2 years... Thx!

**Comment by ericraymond** [comment]
Thanks, that fixes that issue, but I get an error when there is a validation error:

**Comment by ericraymond** [comment]
2018-03-12T17:40:29.591Z - error: uncaughtException: parts.join is not a function date=Mon Mar 12 2018 10:40:29 GMT-0700 (PDT), pid=36720, uid=501, gid=20, cwd=/Users/ericraymond/src/omni/mm/mm-spark/ci/sjs/config/emr, execPath=/usr/local/Cellar/node/9.8.0/bin/node, version=v9.8.0, argv=[/usr/local/Cellar/node/9.8.0/bin/node, /usr/local/bin/cfn-lint, validate, cloudformation/mm.yaml], rss=43294720, heapTotal=23748608, heapUsed=15801488, external=16800, loadavg=[2.31005859375, 2.14990234375, 2.1142578125], uptime=261045, trace=[column=18, file=/usr/local/lib/node_modules/cfn-lint/src/validator.ts, function=fnJoin, line=1053, method=null, native=false, column=16, file=/usr/local/lib/node_modules/cfn-lint/src/validator.ts, function=doIntrinsicJoin, line=596, method=null, native=false, column=20, file=/usr/local/lib/node_modules/cfn-lint/src/validator.ts, function=resolveIntrinsicFunction, line=519, method=null, native=false, column=38, file=/usr/local/lib/node_modules/cfn-lint/src/validator.ts, function=recursiveDecent, line=471, method=null, native=false, column=13, file=/usr/local/lib/node_modules/cfn-lint/src/validator.ts, function=recursiveDecent, line=481, method=null, native=false, column=13, file=/usr/local/lib/node_modules/cfn-lint/src/validator.ts, function=recursiveDecent, line=481, method=null, native=false, column=13, file=/usr/local/lib/node_modules/cfn-lint/src/validator.ts, function=recursiveDecent, line=481, method=null, native=false, column=13, file=/usr/local/lib/node_modules/cfn-lint/src/validator.ts, function=recursiveDecent, line=481, method=null, native=false, column=13, file=/usr/local/lib/node_modules/cfn-lint/src/validator.ts, function=recursiveDecent, line=481, method=null, native=false, column=5, file=/usr/local/lib/node_modules/cfn-lint/src/validator.ts, function=resolveReferences, line=441, method=null, native=false], stack=[TypeError: parts.join is not a function,     at fnJoin (/usr/local/lib/node_modules/cfn-lint/src/validator.ts:1053:18),     at doIntrinsicJoin (/usr/local/lib/node_modules/cfn-lint/src/validator.ts:596:16),     at resolveIntrinsicFunction (/usr/local/lib/node_modules/cfn-lint/src/validator.ts:519:20),     at recursiveDecent (/usr/local/lib/node_modules/cfn-lint/src/validator.ts:471:38),     at recursiveDecent (/usr/local/lib/node_modules/cfn-lint/src/validator.ts:481:13),     at recursiveDecent (/usr/local/lib/node_modules/cfn-lint/src/validator.ts:481:13),     at recursiveDecent (/usr/local/lib/node_modules/cfn-lint/src/validator.ts:481:13),     at recursiveDecent (/usr/local/lib/node_modules/cfn-lint/src/validator.ts:481:13),     at recursiveDecent (/usr/local/lib/node_modules/cfn-lint/src/validator.ts:481:13),     at resolveReferences (/usr/local/lib/node_modules/cfn-lint/src/validator.ts:441:5)]

**Comment by ADRDev** [comment]
Still not fixed?
